[package]
name = "artirat_server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
arti-client = { version = "0.41.0", features = ["onion-service-service", "onion-service-client", "experimental-api"] }
base64 = "0.22.1"
data-encoding = "2.11.0"
futures = "0.3.32"
futures-util = "0.3.32"
rustyline = { version = "18.0.0", features = ["buffer-redux", "signal-hook"] }
tokio = { version = "1.52.2", features = ["full"] }
tor-cell = "0.41.0"
tor-hscrypto = "0.41.0"
tor-hsservice = "0.41.0"
tor-llcrypto = "0.41.0"
tor-proto = "0.41.0"

[build-dependencies]
data-encoding = "2.11.0"
ed25519-dalek = "2.2.0"
rand = "0.8"
sha3 = "0.10"
