#cargo-features = ["panic--abort"]
[package]
name = "artirat_client"
version = "0.2.2"
edition = "2024"

[lib]
crate-type = ["lib", "cdylib"]

[features]
shared-lib = []

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3.9", features=[
    "libloaderapi",
    "minwindef"
] }
windows = { version = "0.62.2", features = [
    "Win32_System_SystemServices",
    "Win32_System_WindowsProgramming",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory"
] }
winres = "0.1.11"
winreg = "0.56.0"
is_elevated = "0.1.2"
windows-sys = { version = "0.61.2", features = ["Win32_UI_WindowsAndMessaging"] }
[dependencies]
arti-client = { version = "0.42", default-features = false, features = ["anyhow", "async-std", "onion-service-client", "accel-openssl", "smol", "static", "static-sqlite", "tokio", "vanguards"] }
gethostname = "1.1.0"
tor-rtcompat = { version = "0.42", features = ["rustls", "tokio"] }
tokio = { version = "1.52.3", features = ["full"] }
anyhow = "1"
rusqlite = { version = "0.39.0", features = ["bundled"] }
zstd = { version = "0.13.3", features = ["zstdmt"] }
openssl = { version = "0.10.79", features = ["vendored"] }
openssl-sys = { version = "0.9.116", features = ["vendored"] }
liblzma-sys = { version = "0.4.6", features = ["static"] }
base64 = "0.22"
libc = { version = "0.2.186", features = ["align", "extra_traits", "use_std"] }
enigo = { version = "0.6.1", features = ["platform_specific", "tokio"] }
rand = { version = "0.8.5", features = [] }
rustls = { version = "0.23.40", features = ["read_buf"] }
encstr = "0.0.1"
[target.'cfg(not(target_os = "android"))'.dependencies]
screenshots = "0.8.10"
[profile.release]
opt-level = "z"
debug = 0
lto = true
codegen-units = 1
strip = true
panic = "abort"
#strip = true
